# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'random-rango' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for random-rango
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn', '~> 5.0'
  pod 'FacebookCore'
  pod 'FacebookLogin'

  target 'random-rangoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'random-rangoUITests' do
    # Pods for testing
  end

end
